const home = {
  id: 0,
  attributes: {
    title: "",
    desc: "",
    currentprice: 0,
    originalprice: 0,
    createdAt: "",
    updatedAt: "",
    publishedAt: "",
    type: "",
    image: {
      data: [
        {
          id: 0,
          attributes: {
            name: "",
            alternativeText: null,
            caption: null,
            width: 0,
            height: 0,
            formats: {
              thumbnail: {
                name: "",
                hash: "",
                ext: "",
                mime: "",
                path: null,
                width: 0,
                height: 0,
                size: 0,
                url: "",
              },
              small: {
                name: "",
                hash: "",
                ext: "",
                mime: "",
                path: null,
                width: 0,
                height: 0,
                size: 0,
                url: "",
              },
            },
            hash: "",
            ext: "",
            mime: "",
            size: 0,
            url: "",
            previewUrl: null,
            provider: "",
            provider_metadata: null,
            createdAt: "",
            updatedAt: "",
          },
        },
      ],
    },
  },
};
export default home;
