const products = {
  id: 1,
  attributes: {
    title: "",
    desc: "",
    createdAt: "2023-05-23T07:36:26.762Z",
    updatedAt: "2023-05-28T11:51:38.096Z",
    publishedAt: "2023-05-23T07:36:34.986Z",
    type: "bracelets",
    currentprice: 249,
    originalprice: 699,
    image: {
      data: [
        {
          id: 15,
          attributes: {
            name: "71Pzqic+ArL._UL1500_.jpg",
            alternativeText: null,
            caption: null,
            width: 1499,
            height: 1500,
            formats: {
              thumbnail: {
                name: "thumbnail_71Pzqic+ArL._UL1500_.jpg",
                hash: "thumbnail_71_Pzqic_Ar_L_UL_1500_1ebbd21a6d",
                ext: ".jpg",
                mime: "image/jpeg",
                path: null,
                width: 156,
                height: 156,
                size: 4.01,
                url: "https://res.cloudinary.com/dc4zxxnuj/image/upload/v1685274431/dripvault/thumbnail_71_Pzqic_Ar_L_UL_1500_1ebbd21a6d.jpg",
                provider_metadata: {
                  public_id:
                    "dripvault/thumbnail_71_Pzqic_Ar_L_UL_1500_1ebbd21a6d",
                  resource_type: "image",
                },
              },
              small: {
                name: "small_71Pzqic+ArL._UL1500_.jpg",
                hash: "small_71_Pzqic_Ar_L_UL_1500_1ebbd21a6d",
                ext: ".jpg",
                mime: "image/jpeg",
                path: null,
                width: 499,
                height: 500,
                size: 25.57,
                url: "https://res.cloudinary.com/dc4zxxnuj/image/upload/v1685274431/dripvault/small_71_Pzqic_Ar_L_UL_1500_1ebbd21a6d.jpg",
                provider_metadata: {
                  public_id: "dripvault/small_71_Pzqic_Ar_L_UL_1500_1ebbd21a6d",
                  resource_type: "image",
                },
              },
              medium: {
                name: "medium_71Pzqic+ArL._UL1500_.jpg",
                hash: "medium_71_Pzqic_Ar_L_UL_1500_1ebbd21a6d",
                ext: ".jpg",
                mime: "image/jpeg",
                path: null,
                width: 750,
                height: 750,
                size: 46.18,
                url: "https://res.cloudinary.com/dc4zxxnuj/image/upload/v1685274431/dripvault/medium_71_Pzqic_Ar_L_UL_1500_1ebbd21a6d.jpg",
                provider_metadata: {
                  public_id:
                    "dripvault/medium_71_Pzqic_Ar_L_UL_1500_1ebbd21a6d",
                  resource_type: "image",
                },
              },
              large: {
                name: "large_71Pzqic+ArL._UL1500_.jpg",
                hash: "large_71_Pzqic_Ar_L_UL_1500_1ebbd21a6d",
                ext: ".jpg",
                mime: "image/jpeg",
                path: null,
                width: 999,
                height: 1000,
                size: 69.4,
                url: "https://res.cloudinary.com/dc4zxxnuj/image/upload/v1685274431/dripvault/large_71_Pzqic_Ar_L_UL_1500_1ebbd21a6d.jpg",
                provider_metadata: {
                  public_id: "dripvault/large_71_Pzqic_Ar_L_UL_1500_1ebbd21a6d",
                  resource_type: "image",
                },
              },
            },
            hash: "71_Pzqic_Ar_L_UL_1500_1ebbd21a6d",
            ext: ".jpg",
            mime: "image/jpeg",
            size: 85.82,
            url: "https://res.cloudinary.com/dc4zxxnuj/image/upload/v1685274431/dripvault/71_Pzqic_Ar_L_UL_1500_1ebbd21a6d.jpg",
            previewUrl: null,
            provider: "cloudinary",
            provider_metadata: {
              public_id: "dripvault/71_Pzqic_Ar_L_UL_1500_1ebbd21a6d",
              resource_type: "image",
            },
            createdAt: "2023-05-28T11:47:11.503Z",
            updatedAt: "2023-05-28T11:47:11.503Z",
          },
        },
      ],
    },
  },
};
export default products;
